name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check kernel
        run: |
          sudo su root
          uname -a
          cat /etc/os-release
          ls -l /proc/sys/net/
          sudo modprobe mpls_iptunnel
          ls -l /proc/sys/net/mpls
          curl -s https://deb.frrouting.org/frr/keys.asc | sudo apt-key add -
          FRRVER="frr-stable"
          echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | sudo tee -a /etc/apt/sources.list.d/frr.list
          sudo apt update && sudo apt install frr frr-pythontools
          sudo -H python3 -V
          sudo -H python3 -m pip install nitk-nest
